#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tle-mign <tle-mign@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2013/11/25 12:25:27 by tle-mign          #+#    #+#              #
#    Updated: 2014/03/12 18:38:35 by tle-mign         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = src

all : $(NAME)

$(NAME) :
		make -C amalias

clean :
			make clean -C amalias

fclean : clean
			make fclean -C amalias

re : fclean all
